language: python
python:
- "3.5"
- "3.6"
- "3.7"
- "3.7-dev"
- "3.8-dev"

install:
- pip install pytest
- pip install pytest-cov
- pip install coveralls

script:
- pytest --cov force_deps/ tests/

after_success:
  - coveralls